\documentclass[a4paper]{article}


%\usepackage{microtype}
\usepackage{tabularx}
\usepackage{booktabs}
\usepackage{siunitx}    
\usepackage{xcolor}
\usepackage{graphicx}
\usepackage{color}
\usepackage{bm}	



\begin{document}


<<>>=
library(kableExtra)
library(dplyr)
text <- data.frame(
Items = c("Item 1", "Item 2", "Item 3"),
Features = c(
"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin vehicula tempor ex. Morbi malesuada sagittis turpis, at venenatis nisl luctus a. ",
"In eu urna at magna luctus rhoncus quis in nisl. Fusce in velit varius, posuere risus et, cursus augue. Duis eleifend aliquam ante, a aliquet ex tincidunt in. ",
"Vivamus venenatis egestas eros ut tempus. Vivamus id est nisi. Aliquam molestie erat et sollicitudin venenatis. In ac lacus at velit scelerisque mattis. "
)
)

kable(text, "latex", booktabs = T) %>%
  kable_styling(full_width = F) %>%
  column_spec(1, bold = T, color = "red") %>%
  column_spec(2, width = "30em")
@


\end{document}